#
# General
#

namespace: shkeeper

dev:
  imagePullSecrets:

storageClassName:

#
# Shkeeper
#

shkeeper:
  image: vsyshost/shkeeper:2.1.52
  port: 5000

#
# BTC and forks
#

btc:
  enabled: true
  mainnet: true
ltc:
  enabled: true
  mainnet: true
doge:
  enabled: true
  mainnet: true

#
# Tron
#

tron_fullnode:
  enabled: false
  url: http://java-tron:8090
  solidity_url: http://java-tron:8091
  mainnet: true
  JAVA_TOOL_OPTIONS: ""
  nodeSelector: {}
  tolerations: []

tron_shkeeper:
  image: vsyshost/tron-shkeeper:1.0.18
  host: 'tron-shkeeper'
  port: 6000

trx:
  enabled: false
usdt:
  enabled: false
usdc:
  enabled: false

#
# Ethereum
#

eth_fullnode:
  enabled: false
  url: http://ethereum:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []

ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper:1.1.4

eth:
  enabled: false
eth_usdt:
  enabled: false
eth_usdc:
  enabled: false

#
# Monero
#

monero:

  enabled: false
  image: vsyshost/monero:v0.18.1.2
  mainnet: true

  fullnode:
    enabled: false
    monerod:
      host: "monerod"
      port: "1111"
      user: "monerod"
      password: "monerod"
      nodeSelector: {}
      tolerations: []

#
# BNB
#

bnb_fullnode:
  enabled: false
  url: http://bnb:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []

bnb_shkeeper:
  image: vsyshost/bnb-shkeeper:1.1.4

bnb:
  enabled: false
bnb_usdt:
  enabled: false
bnb_usdc:
  enabled: false

#
# XRP
#

xrp_fullnode:
  enabled: false
  url: http://xrp:51234
  mainnet: true
  nodeSelector: {}
  tolerations: []

xrp_shkeeper:
  image: vsyshost/xrp-shkeeper:1.0.11

xrp:
  enabled: false

#
# Polygon
#

polygon_fullnode:
  enabled: false
  url: http://polygon:51234
  mainnet: true
  nodeSelector: {}
  tolerations: []

polygon_shkeeper:
  image: vsyshost/polygon-shkeeper:1.0.3

matic:
  enabled: false
polygon_usdt:
  enabled: false
polygon_usdc:
  enabled: false

#
# Avalanche
#

avalanche_fullnode:
  enabled: false
  url: http://avalanche:9650/ext/bc/C/rpc
  mainnet: true
  nodeSelector: {}
  tolerations: []

avalanche_shkeeper:
  image: vsyshost/avalanche-shkeeper:1.0.0

avax:
  enabled: false
avalanche_usdt:
  enabled: false
avalanche_usdc:
  enabled: false