{{ if .Values.btc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: jsonrpc
    port: 8332
    protocol: TCP
    targetPort: 8332
  - name: nginx
    port: 5555
    protocol: TCP
    targetPort: 80
  selector:
    app: bitcoind
{{ end }}