apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-docker-entrypoint-initdb-d
  namespace: {{ .Values.namespace }}
data:
  create_db.sql: |
    CREATE DATABASE IF NOT EXISTS `shkeeper`;
    CREATE DATABASE IF NOT EXISTS `ethereum-shkeeper`;
    CREATE DATABASE IF NOT EXISTS `bnb-shkeeper`;
    CREATE DATABASE IF NOT EXISTS `xrp-shkeeper`;
    CREATE DATABASE IF NOT EXISTS `polygon-shkeeper`;
    CREATE DATABASE IF NOT EXISTS `avalanche-shkeeper`;

  my.cnf: |
    [mysqld]
    max_connections = 500
    # You can add other configuration settings as needed
